ALTER TABLE incident_comment
    ADD COLUMN IF NOT EXISTS author_type VARCHAR(20) NOT NULL DEFAULT 'USER';

ALTER TABLE issue_comment
    ADD COLUMN IF NOT EXISTS author_type VARCHAR(20) NOT NULL DEFAULT 'USER';

ALTER TABLE issue_comment
    ADD COLUMN IF NOT EXISTS is_public BOOLEAN NOT NULL DEFAULT true;
