ALTER TABLE notification_preference
    ADD COLUMN IF NOT EXISTS notify_status_change BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS notify_assignment     BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS notify_comment        BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS notify_mention        BOOLEAN NOT NULL DEFAULT TRUE;
